spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:56387/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=PLDRJvvlhnTMfEccCTxVXJdLpHuZCAeZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
