ALTER TABLE books ADD COLUMN IF NOT EXISTS isbn VARCHAR(32);

UPDATE books
SET isbn = 'ISBN-' || LPAD(CAST(id AS VARCHAR), 10, '0')
WHERE isbn IS NULL;

ALTER TABLE books ALTER COLUMN isbn SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_books_isbn ON books (isbn);
