spring.application.name=andrius-web-app
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:${POSTGRES_HOST:postgres.railway.internal}}:${PGPORT:${POSTGRES_PORT:5432}}/${PGDATABASE:${POSTGRES_DB:railway}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:${POSTGRES_USER:postgres}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:${POSTGRES_PASSWORD:PLDRJvvlhnTMfEccCTxVXJdLpHuZCAeZ}}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
